//file:noinspection GradlePackageVersionRange
plugins {
    id 'net.fabricmc.fabric-loom' version '1.17-SNAPSHOT'
    id 'maven-publish'
}

version = "${project.mod_version}+${project.minecraft_base_version}"
group = project.maven_group

repositories {
    maven { url = "https://maven.wispforest.io/" }
    maven { url = "https://jitpack.io" }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"

    // Fabric API
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

        implementation("io.wispforest:endec:0.1.12")
}

base {
    archivesName = project.archives_base_name
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

loom {
    accessWidenerPath = file("src/main/resources/numismatic-overhaul.accesswidener")
}


java {
    withSourcesJar()
}

tasks.withType(JavaCompile).configureEach {
    // options.release = 21
}

jar {
    from("LICENSE") {
        rename { "${it}_${base.archivesName.get()}"}
    }
}
