# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G

# Fabric Properties
minecraft_base_version=26
minecraft_version=26.2
loader_version=0.19.3

# Mod Properties
mod_version=0.3.5
maven_group=com.glisco
archives_base_name=numismatic-overhaul

# Dependencies
fabric_version=0.152.2+26.2
